# Generated by Django 5.2.7 on 2026-08-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filemanager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("upload", "File Upload"),
                    ("download", "File Download"),
                    ("delete", "File Delete"),
                    ("view", "File View"),
                    ("rename", "File Rename"),
                ],
                max_length=10,
            ),
        ),
    ]
